services:
  - type: web
    name: movie-recommendation-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        scope: build
      - key: PORT
        value: 5000
    disk:
      name: database
      mountPath: /app
      sizeGB: 1
